Repository JobCoordi/FE, pull requests merged in 2025-04, with the labels that each got.

#18 Input 레이아웃
  src/app/testpage/page.tsx
  src/components/common/Button/.gitkeep
  src/components/common/Button/index.tsx
  src/components/common/Input/index.tsx
  src/types/button.ts
  src/types/input.ts
Labels: 리팩토링, 컴포넌트

#26 Chatbubble 레이아웃
  src/app/chat/page.tsx
  src/app/testpage/page.tsx
  src/components/common/ChatAnswer/.gitkeep
  src/components/common/ChatBubble/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Modal/index.tsx
  src/types/chatbubble.ts
  src/types/input.ts
Labels: 레이아웃, 컴포넌트

#23 chat-page 레이아웃
   변경" " ; 
  src/app/chat/page.tsx
  src/app/layout.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/app/testpage/page.tsx
  src/components/common/ChatAnswer/.gitkeep
  src/components/common/ChatBubble/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Nav/index.tsx
  src/components/product/chat/.gitkeep
  src/components/product/sign/.gitkeep
  src/types/chatbubble.ts
  src/types/input.ts
Labels: 레이아웃, 페이지

#32 chat-page 디자인
  src/app/chat/page.tsx
  src/app/testpage/page.tsx
  src/components/common/Button/index.tsx
  src/components/common/ChatBubble/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Modal/index.tsx
  src/components/product/chat/chatform.tsx
  src/hooks/useModal.tsx
  src/hooks/useResizeInput.tsx
  src/styles/globals.css
  src/types/chatform.ts
  src/types/input.ts
Labels: 디자인, 페이지

#39 main-page의 레이아웃 section1 작업
  components.json
  package-lock.json
  package.json
  src/app/chat/page.tsx
  src/app/page.tsx
  src/app/testpage/page.tsx
  src/components/common/Button/index.tsx
  src/components/common/ChatBubble/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Nav/index.tsx
  src/components/product/chat/chatform.tsx
  src/components/product/main/ImageSection.tsx
  src/components/product/main/LinkSection.tsx
  src/components/product/main/TextSeciton.tsx
  src/components/ui/demo.tsx
  src/components/ui/text-rotate.tsx
  src/hooks/useModal.tsx
  src/hooks/useResizeInput.tsx
  src/lib/utils.ts
  src/mock/cards.ts
  src/styles/globals.css
  src/types/button.ts
  src/types/chatbubble.ts
  src/types/chatform.ts
  src/types/input.ts
  tailwind.config.ts
Labels: 레이아웃, 페이지

#42 FloatingButton 레이아웃
  src/app/result/page.tsx
  src/components/common/FloatingButton/index.tsx
  src/types/floatingbutton.ts
Labels: 디자인, 컴포넌트

#46 mainPage의 기능 작업
  components.json
  package-lock.json
  package.json
  public/image/1.jpeg
  public/image/2.jpeg
  public/image/3.jpg
  public/image/4.jpeg
  public/image/5.jpeg
  public/image/6.jpeg
  public/image/7.jpeg
  public/image/8.jpg
  src/app/chat/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/result/page.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/app/testpage/page.tsx
  src/components/common/Button/index.tsx
  src/components/common/ChatAnswer/.gitkeep
  src/components/common/FloatingButton/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Nav/index.tsx
  src/components/product/chat/.gitkeep
  src/components/product/chat/chatform.tsx
  src/components/product/main/ImageSection.tsx
  src/components/product/main/LinkSection.tsx
  src/components/product/main/RotateSection.tsx
  src/components/product/main/TextSeciton.tsx
  src/components/product/main/homeContent.tsx
  src/components/product/sign/.gitkeep
  src/components/ui/demo.tsx
  src/components/ui/text-rotate.tsx
  src/hooks/useModal.tsx
  src/hooks/useResizeInput.tsx
  src/hooks/useSmoothScroll.tsx
  src/lib/utils.ts
  src/mock/cards.ts
  src/styles/globals.css
  src/types/button.ts
  src/types/chatform.ts
  src/types/floatingbutton.ts
  src/types/input.ts
  tailwind.config.ts
  tsconfig.json
Labels: 기능, 페이지

#50 FloatingButton 기능 구현 (다크모드, 상단이동)
  components.json
  package-lock.json
  package.json
  public/image/1.jpeg
  public/image/2.jpeg
  public/image/3.jpg
  public/image/4.jpeg
  public/image/5.jpeg
  public/image/6.jpeg
  public/image/7.jpeg
  public/image/8.jpg
  src/app/chat/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/result/page.tsx
  src/app/testpage/page.tsx
  src/components/common/FloatingButton/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Nav/index.tsx
  src/components/common/Toggle/index.tsx
  src/components/product/chat/chatform.tsx
  src/components/product/main/ImageSection.tsx
  src/components/product/main/LinkSection.tsx
  src/components/product/main/RotateSection.tsx
  src/components/product/main/TextSeciton.tsx
  src/components/ui/demo.tsx
  src/components/ui/text-rotate.tsx
  src/hooks/useSmoothScroll.tsx
  src/lib/utils.ts
  src/mock/cards.ts
  src/styles/globals.css
  src/types/floatingbutton.ts
  src/types/toggle.ts
  tailwind.config.ts
  tsconfig.json
Labels: 기능, 컴포넌트

#51 chatPage의 기능 작업
  components.json
  package-lock.json
  package.json
  public/image/1.jpeg
  public/image/2.jpeg
  public/image/3.jpg
  public/image/4.jpeg
  public/image/5.jpeg
  public/image/6.jpeg
  public/image/7.jpeg
  public/image/8.jpg
  src/app/chat/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/result/page.tsx
  src/app/testpage/page.tsx
  src/components/common/Button/index.tsx
  src/components/common/ChatBubble/index.tsx
  src/components/common/FloatingButton/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Nav/index.tsx
  src/components/product/chat/chatform.tsx
  src/components/product/main/ImageSection.tsx
  src/components/product/main/LinkSection.tsx
  src/components/product/main/RotateSection.tsx
  src/components/product/main/TextSeciton.tsx
  src/components/product/main/homeContent.tsx
  src/components/ui/demo.tsx
  src/components/ui/text-rotate.tsx
  src/hooks/useSmoothScroll.tsx
  src/lib/utils.ts
  src/libs/auth/postAuth.ts
  src/libs/chat/postChat.ts
  src/libs/instance.ts
  src/mock/cards.ts
  src/styles/globals.css
  src/types/button.ts
  src/types/chatbubble.ts
  src/types/chatform.ts
  src/types/floatingbutton.ts
  src/types/input.ts
  src/types/postChat.ts
  tailwind.config.ts
  tsconfig.json
Labels: 기능, 페이지

#55 mainPage의 리팩토링과 chatPage 오류 해결
  package-lock.json
  package.json
  src/app/chat/page.tsx
  src/app/page.tsx
  src/components/common/Button/index.tsx
  src/components/product/chat/chatform.tsx
  src/components/product/main/ImageSection.tsx
  src/components/product/main/RotateSection.tsx
  src/components/product/main/SectionWrapper.tsx
  src/components/product/main/TextSeciton.tsx
  src/components/ui/demo.tsx
  src/styles/globals.css
Labels: 리팩토링, 페이지

#78 카드 레이아웃
  src/app/result/page.tsx
  src/components/common/Card/.gitkeep
  src/components/common/Card/index.tsx
  src/mock/resultCard.ts
  src/types/card.ts
Labels: 레이아웃, 컴포넌트

#82 페이지네이션 레이아웃
  package-lock.json
  package.json
  src/app/result/page.tsx
  src/components/common/Button/index.tsx
  src/components/common/Pagination/.gitkeep
  src/components/common/Pagination/index.tsx
  src/mock/resultCard.ts
  src/types/button.ts
Labels: 레이아웃, 컴포넌트

#84 플로팅버튼 리팩토링
  public/icon/ic_end.svg
  src/app/chat/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/FloatingButton/index.tsx
  src/components/common/Toggle/index.tsx
  src/hooks/useScrollVisibility.tsx
  src/types/floatingbutton.ts
  src/types/toggle.ts
Labels: 리팩토링, 컴포넌트

#87 폼 리팩토링
  src/app/chat/page.tsx
  src/components/common/Button/index.tsx
  src/components/product/chat/chatform.tsx
  src/types/chatform.ts
Labels: 리팩토링, 페이지

#88 폼 리팩토링
  src/components/product/chat/chatform.tsx
Labels: 리팩토링
